# Generated by Django 4.2 on 2023-04-16 11:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('polygon', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added', models.DateTimeField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('geolocation', models.JSONField()),
                ('visited', models.DateTimeField(blank=True, null=True)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('neighborhood', models.ManyToManyField(to='restlist.neighborhood')),
            ],
        ),
    ]
