# Generated by Django 4.2 on 2023-05-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restlist', '0003_alter_neighborhood_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='level',
            field=models.SmallIntegerField(),
        ),
    ]
